// Dependencies:
// https://github.com/catchorg/Catch2

// Generated by Qodo Gen

#include <catch2/catch_test_macros.hpp>
#include <cstdint>

TEST_CASE("ElfAarch64Validator") {


    // Successfully validate a valid AArch64 ELF file
    SECTION("should correctly identify a valid AArch64 ELF file") {
        // Create a temporary file with AArch64 ELF header
        std::string temp_filename = "temp_aarch64.elf";
        std::ofstream temp_file(temp_filename, std::ios::binary);
    
        // Create minimal valid ELF header
        Elf64_Ehdr header;
        memcpy(header.e_ident, ELFMAG, SELFMAG);  // Set ELF magic number
        header.e_ident[EI_CLASS] = ELFCLASS64;    // Set as 64-bit
        header.e_machine = EM_AARCH64;            // Set as AArch64
    
        // Write header to file
        temp_file.write(reinterpret_cast<char*>(&header), sizeof(header));
        temp_file.close();
    
        // Test the validator
        ElfAarch64Validator validator(temp_filename);
        REQUIRE(validator.open_file() == true);
        REQUIRE(validator.is_aarch64() == true);
    
        // Clean up
        std::remove(temp_filename.c_str());
    }

    // Attempt to validate a non-existent file
    SECTION("should fail when opening a non-existent file") {
        // Use a filename that doesn't exist
        std::string nonexistent_file = "this_file_does_not_exist.elf";
    
        // Test the validator
        ElfAarch64Validator validator(nonexistent_file);
        REQUIRE(validator.open_file() == false);
    
        // Since open_file failed, is_aarch64 should also fail
        REQUIRE(validator.is_aarch64() == false);
    }
}